spring:
  application:
    name: jsonmap
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/testdb

  datasource:
    url: jdbc:postgresql://localhost:5432/mapper
    username: mapper
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8084


